### ISSUE TITLE
Schema Link Returns 404

### ISSUE THREAD

**Issue by epuio** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#120]
The following is included in many (if not all) of the XML files:

`xmlns="http://schemas.microsoft.com/online/cpim/schemas/2013/06"`

That URL is returning a 404. Is it possible to get the latest URL? I realize the files will also need to be updated but was hoping that I could get the URL in the meantime.

Thank you

**Comment by yoelhor** [comment]
The `xmlns` attribute specifies the `xs` namespace for the xml document. The namespace URI is not used by the parser to look up information. The purpose of using an URI is to give the namespace a unique name. However, companies often use the namespace as a pointer to a web page containing namespace information. For more information, see [w3schools XML Namespaces](https://www.w3schools.com/xml/xml_namespaces.asp).
