### ISSUE TITLE
Email Regular Expression for email claim accepting invalid emails

### ISSUE THREAD

**Issue by arath17** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#129]
The regular expression for email claim validation is accepting invalid email formats such as 'name@gmail'

**Comment by yoelhor** [comment]
Closing the issue due to the fix https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/commit/29424bc7a580c1ac8466d1200d14b8d37a7e8fff
