### ISSUE TITLE
Azure B2C custom policies can't integrate with API Management

### ISSUE THREAD

**Issue by ndquoc** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#24]
I tried to config Azure B2C using custom policies and API Management Identities but it was not success.

1. When i used Azure B2C built-in policies, it worked perfectly.

2. When i used Azure B2C custom policies (with [xml files](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/SocialAndLocalAccounts)), the Azure B2C provider appeared on APIM login page. After login success, i got an error message "**Authentication has failed.**"

Does Azure B2C custom polices support APIM identities?

**Comment by sirdank** [comment]
@ndquoc Did you get any resolution on this?
