### ISSUE TITLE
alternativeSecurityId case sensitivity issue?

### ISSUE THREAD

**Issue by naiduv** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#51]
https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/d20bb35939124503f10661963c5e3129603eea95/SocialAndLocalAccounts/TrustFrameworkBase.xml#L575

https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/d20bb35939124503f10661963c5e3129603eea95/SocialAndLocalAccounts/TrustFrameworkBase.xml#L579

Why are the cases different in the 2 lines? Does this work as is?

**Comment by xinaxu** [comment]
The name of the claim type is case insensitive. the value is case sensitive.
