### ISSUE TITLE
Rejects some valid e-mails

### ISSUE THREAD

**Issue by agentsim** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#52]
When doing development, it is often useful to use emails of the form:

`my_email+1234@my_domain.com`

E-mails of this form are rejected by the regular expression in `TrustFrameworkBase.xml`

**Comment by beezital** [comment]
@agentsim 
In your `TrustFrameworkExtensions.xml` add following block that contains a RegularException that includes the plus sign ("+") as an allowed character.
```
  <BuildingBlocks>

    <ClaimsSchema>
      <ClaimType Id="email">
        <Restriction>
          <!-- added plus sign ("+") to the regex to allow gmail suffixed virtual addresses -->
          <!-- <Pattern RegularExpression="^[a-zA-Z0-9.!#$%&amp;'^_`{}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$" HelpText="Please enter a valid email address." /> -->
          <Pattern RegularExpression="^[+a-zA-Z0-9.!#$%&amp;'^_`{}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$" HelpText="Please enter a valid email address." />
        </Restriction>
      </ClaimType>
    </ClaimsSchema>

  </BuildingBlocks>
```

**Comment by jpda** [comment]
Emails with subdomain suffixes also fail (e.g., something@sub.example.com)

**Comment by LockTar** [comment]
> When doing development, it is often useful to use emails of the form:
> 
> `my_email+1234@my_domain.com`
> 
> E-mails of this form are rejected by the regular expression in `TrustFrameworkBase.xml`

I had exactly the same issue so I created a Microsoft ticket for this. The've updated the samples with their regular expression. [See this commit.](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/commit/29424bc7a580c1ac8466d1200d14b8d37a7e8fff)
They use this regular expression in the User flow experience.
Not tested this my self but should solve the issue.

**Comment by yoelhor** [comment]
Closing the issue due to the fix https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/commit/29424bc7a580c1ac8466d1200d14b8d37a7e8fff
