### ISSUE TITLE
Split the signup screen into 2 screens

### ISSUE THREAD

**Issue by tiwari-abhishek** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#59]
The signup page on AD B2C shows the email verification controls followed by user First name Last name and other fields.

I would like to split this into 2 separate screens where the users only see the email verification box and send the verification code. When they comeback they should be able to go to the next screen which asks for more details.

For multiple projects here, we do not like having it all on one screen, basically it doesn't make sense to show controls that are not relevant to what we are trying to do, i.e. just email verification before anything else.

So the question is, is that possible. Has anyone tried it? Can you share any customization samples, pointers?

**Comment by tiwari-abhishek** [comment]
I found a way to do it. Here is the link to the policy in case anyone needs it:
https://github.com/tiwari-abhishek/samples/blob/master/policies/split-email-verification-and-signup

**Comment by alekfestekjian** [comment]
I uploaded this custom policy but how to I integrate it with my existing SignUpOrSignin.xml from the Starterpack? I'm a bit confused how to integrate this policy if I started off with uploading the starterpack.

**Comment by hrc7505** [comment]
It will be easier if we have this option to choose in flows?
