### ISSUE TITLE
How to get the base-v1 policy

### ISSUE THREAD

**Issue by sven5** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#66]
We're using Azure AD B2C for a client app. I configured many custom claim properties and several user journeys through the Azure portal.
However, now we need some special functionality that can only be achieved by directly editing the policy xml files because Azure Portal doesn't support these features.

But I don't want to start from scratch with the xml templates as it seems to be very difficult.

Now my question is:
Is it possble to get the current working base policy as xml file? It's not possible to derive my own custom policy from the default base-v1 policy.

**Comment by sudolibre** [comment]
This may not be officially supported but I recall getting that file by looking that the request it was making from the browser when I downloaded a particular policy and noticed there was a query param called 'getBasePolicies' which was set to false. I copied that request and made it again with the param set to true and it included the base policy in the response.

**Comment by sven5** [comment]
Hi @sudolibre 

Thanks for that hint. Could you please describe the way you are making requests from the browser?
Currently, I only worked with Azure Portal and with the [B2cPolicyManager ](https://github.com/azure-ad-b2c/custom-policy-manager) application.

**Comment by sven5** [comment]
Ok I was able to get all the base policy settings with the help of this blog post:
https://blog.wojtek.pro/azure-ad-b2c-custom-policies-how-to-begin/
