### ISSUE TITLE
TrustFrameworkPolicy XSD seems outdated

### ISSUE THREAD

**Issue by SaurabhSharma-MSFT** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#71]
Where can I find the XSD for the TrustFrameworkPolicy XML?
I found one in some Azure Samples github repository (https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack), but it obviously does not fully match the description in the Azure Documentation.
Just one example out of many: The XSD does not have an "Enabled" attribute on the "Localization" element, whereas the documentation lists it.

Ref: [GitHub Issue](https://github.com/MicrosoftDocs/azure-docs/issues/61151)

**Comment by renidantass** [comment]
SaurabhSharma some news? I think this is a important part for developing custom policies.

**Comment by philip-young** [comment]
Hello @SaurabhSharma-MSFT , I have raised this issue as well some time ago. It causes frustration because you can never get your XML to fully validate (which is one of the purposes of having an XSD file). For more details on some issues I came across, see here: https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/issues/62

**Comment by jskop** [comment]
Hello, I've found another error  when reading ClaimsTransformation section for Azure B2C custom policies. See [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/62254)

**Comment by jskop** [comment]
Schema is also missing Predicates and DisplayControls nodes - both described in Azure docs. Schema defines node ClientDefinitions which is not contained in schema.

**Comment by rbrayb** [comment]
The xsd has not been updated for phone number SUSI.

"<DataType>phoneNumber</DataType>" gives errors.

**Comment by TheUniquePaulSmith** [comment]
I have the same issue with TrustFrameworkPolicy XSD being outdated.
We have built a CI/CD Pipeline in ADO that uses this XSD to validate custom policies, but there are missing definitions compared to what is documented in online in B2C policies.

Please refer to my pull request which addresses some of these items: #88

**Comment by KevinCathcart** [comment]
There is an updated XSD file available in the [source code of the Visual Studio Code extension](https://github.com/azure-ad-b2c/vscode-extension/blob/e73bca503be78b3ec16c665a477fb4bf17642845/src/Consts.ts#L736).

That file appears to have all the current elements, both documented and not documented. It is not quite completely up to date, as it is missing the claim data types `objectIdentity` and `objectIdentityCollection`, but if you add those it seems to be able to verify the built-in base policy, which does not even come close to validating with the current schema in this repository. It seems clear that an up-to-date schema is being maintained in source control somewhere, but it is not clear if said schema gets published anywhere publicly accessible. 

Perhaps @yoelhor can comment? He was the last one to update the schema in the VSCode extension, so at the very least he should know how where he got the updated schema from.

**Comment by yoelhor** [comment]
The XSD is updated with the latest version.
