### ISSUE TITLE
Generic exception "server_error, AADB2C: An exception has occured"

### ISSUE THREAD

**Issue by rajeshmag** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#8]
Using custom SignUp_SignIn policy for SocialAndLocalAccounts, I am getting below exception each time I try to authenticate with a social account (Facebook)

ErrorMessage: server_error
ErrorDescription:
AADB2C: An exception has occured.
Correlation ID: 9f92fe54-31e6-4ff8-8145-399311128ef8
Timestamp: 2017-08-14 06:24:34Z

The exception only occurs when I use custom policies in the AD B2C Identity Experience Framework. When tried with default Sign-up or sign-in policy with Facebook Identity provider, it works perfectly well.

**Comment by parakhj** [comment]
Did you try following [these steps](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-get-started-custom#next-steps)? Also try [setting up application insights](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-troubleshoot-custom) to get more logs if it is still failing.

**Comment by rajeshmag** [comment]
Thank you very much for the help, the problem is solved!

The problem was incorrect Facebook secret. Switching to a different Facebook application in the policy file, missed updating the Policy Key for FacebookSecret. Fortunately, it was captured in App Insights as below:
""Message"": ""An exception was caught when making a request to URL \""https://graph.facebook.com/oauth/access_token\"" using method \""Get\"". The exception status code was \""ProtocolError\"" with the following message: The remote server returned an error: (400) Bad Request..""
